Skip some of credentials and sources tests if sshkeyfile is missing in configuration
Before:

FAILED camayoc/tests/qpc/cli/test_credentials.py::test_add_with_username_sshkeyfile - camayoc.exceptions.NoMatchingDataDefinitionException: No data matching provided criteria. Try changing 'match_criteria' or revi...
FAILED camayoc/tests/qpc/cli/test_credentials.py::test_add_with_username_sshkeyfile_become_password - camayoc.exceptions.NoMatchingDataDefinitionException: No data matching provided criteria. Try changing 'match_criteria' or revi...
FAILED camayoc/tests/qpc/cli/test_credentials.py::test_edit_sshkeyfile_negative - camayoc.exceptions.NoMatchingDataDefinitionException: No data matching provided criteria. Try changing 'match_criteria' or revi...
...

After:

SKIPPED [1] camayoc/tests/qpc/cli/test_credentials.py:140: Make sure you have at least one network credential with sshkeyfile on the config file to run this test.
SKIPPED [1] camayoc/tests/qpc/cli/test_credentials.py:178: Make sure you have at least one network credential with sshkeyfile on the config file to run this test.
SKIPPED [1] camayoc/tests/qpc/cli/test_credentials.py:376: Make sure you have at least one network credential with sshkeyfile on the config file to run this test.
...
SKIPPED [3] camayoc/tests/qpc/api/v1/sources/test_network_sources.py:79: Make sure you have at least one network credential with sshkeyfile on the config file to run this test.
SKIPPED [4] camayoc/tests/qpc/api/v1/sources/test_network_sources.py:115: Make sure you have at least one network credential with sshkeyfile on the config file to run this test.