Issues/316 (#328)
* Started adding yupana test section

* renamed test_config.py to test_connect.py and added make command for yupana tests

* Revert "Added simple test to send file and check response status code"

This reverts commit 16828375407138123d43f3802bbe4193a654a1b5.

* Cleaned up and added test to send file to upload-service

* Fixed some lint errors

* Switched ============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-5.0.0, py-1.8.0, pluggy-0.12.0
rootdir: /home/ryan/Documents/code/camayoc, inifile: pytest.ini
plugins: cov-2.7.1
collected 617 items / 1 errors / 616 selected

==================================== ERRORS ====================================
____________ ERROR collecting camayoc/tests/remote/rho/test_scan.py ____________
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/python.py:1166: in _idval
    generated_id = idfn(val)
camayoc/tests/remote/rho/test_scan.py:209: in get_permutation_id
    return param.get("name") or param.get("hostname")
E   AttributeError: 'str' object has no attribute 'get'

The above exception was the direct cause of the following exception:
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/pluggy/hooks.py:289: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/pluggy/manager.py:87: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/pluggy/manager.py:81: in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/python.py:225: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/python.py:401: in _genfunctions
    self.ihook.pytest_generate_tests(metafunc=metafunc)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/pluggy/hooks.py:289: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/pluggy/manager.py:87: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/pluggy/manager.py:81: in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/python.py:128: in pytest_generate_tests
    metafunc.parametrize(*marker.args, **marker.kwargs)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/python.py:1004: in parametrize
    ids = self._resolve_arg_ids(argnames, ids, parameters, item=self.definition)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/python.py:1058: in _resolve_arg_ids
    ids = idmaker(argnames, parameters, idfn, ids, self.config, item=item)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/python.py:1210: in idmaker
    for valindex, parameterset in enumerate(parametersets)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/python.py:1210: in <listcomp>
    for valindex, parameterset in enumerate(parametersets)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/python.py:1200: in _idvalset
    for val, argname in zip(parameterset.values, argnames)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/python.py:1200: in <listcomp>
    for val, argname in zip(parameterset.values, argnames)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/python.py:1173: in _idval
    raise ValueError(msg) from e
E   ValueError: camayoc/tests/remote/rho/test_scan.py::test_scan: error raised while trying to determine id of parameter 'machine' at position 0
=============================== warnings summary ===============================
camayoc/config.py:36
  /home/ryan/Documents/code/camayoc/camayoc/config.py:36: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
    _CONFIG = yaml.load(f)

/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
  /home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
    args, varargs, keywords, defaults = inspect.getargspec(method)

/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/mark/structures.py:332
  /home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/mark/structures.py:332: PytestUnknownMarkWarning: Unknown pytest.mark.troubleshoot - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
===================== 14 warnings, 1 error in 1.42 seconds ===================== to ============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-5.0.0, py-1.8.0, pluggy-0.12.0
rootdir: /home/ryan/Documents/code/camayoc, inifile: pytest.ini
plugins: cov-2.7.1
collected 617 items / 1 errors / 616 selected

==================================== ERRORS ====================================
____________ ERROR collecting camayoc/tests/remote/rho/test_scan.py ____________
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/python.py:1166: in _idval
    generated_id = idfn(val)
camayoc/tests/remote/rho/test_scan.py:209: in get_permutation_id
    return param.get("name") or param.get("hostname")
E   AttributeError: 'str' object has no attribute 'get'

The above exception was the direct cause of the following exception:
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/pluggy/hooks.py:289: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/pluggy/manager.py:87: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/pluggy/manager.py:81: in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/python.py:225: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/python.py:401: in _genfunctions
    self.ihook.pytest_generate_tests(metafunc=metafunc)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/pluggy/hooks.py:289: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/pluggy/manager.py:87: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/pluggy/manager.py:81: in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/python.py:128: in pytest_generate_tests
    metafunc.parametrize(*marker.args, **marker.kwargs)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/python.py:1004: in parametrize
    ids = self._resolve_arg_ids(argnames, ids, parameters, item=self.definition)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/python.py:1058: in _resolve_arg_ids
    ids = idmaker(argnames, parameters, idfn, ids, self.config, item=item)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/python.py:1210: in idmaker
    for valindex, parameterset in enumerate(parametersets)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/python.py:1210: in <listcomp>
    for valindex, parameterset in enumerate(parametersets)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/python.py:1200: in _idvalset
    for val, argname in zip(parameterset.values, argnames)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/python.py:1200: in <listcomp>
    for val, argname in zip(parameterset.values, argnames)
../../../.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/python.py:1173: in _idval
    raise ValueError(msg) from e
E   ValueError: camayoc/tests/remote/rho/test_scan.py::test_scan: error raised while trying to determine id of parameter 'machine' at position 0
=============================== warnings summary ===============================
camayoc/config.py:36
  /home/ryan/Documents/code/camayoc/camayoc/config.py:36: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
    _CONFIG = yaml.load(f)

/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163
  /home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/aenum/__init__.py:163: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
    args, varargs, keywords, defaults = inspect.getargspec(method)

/home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/mark/structures.py:332
  /home/ryan/.local/share/virtualenvs/camayoc-kBDoRrxj/lib/python3.6/site-packages/_pytest/mark/structures.py:332: PytestUnknownMarkWarning: Unknown pytest.mark.troubleshoot - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
===================== 14 warnings, 1 error in 1.35 seconds ===================== in Makefile.
Also, removed empty yupana conftest.py for now

* Added assert feedback string, added inventory-service config check

* Fixed 'test_qpc_url_no_hostname' camayoc test

* Fixed deprecated yaml load

* Updated docstrings to meet requirements

* add

* switch to oc package

* Added functions to search logs of multiple pods. Needs cleaning.

* Search partial function line was messed up

* Switched yupana_config to be a fixture. Also moved preliminary pod log test assertions to the file upload test.

* Ran black formatter

* Pulled out upload file into a class fixture for tests.

* Fixed docstring issue

* added some more upload tests

* Applying the pydocstyle 3.0.0 fix to the branch

* Fixed linting issue with regex string

* Added feed back from PR review
Pulled regex out into a constant variable
Switch oc_setup to be a fixture, and added a set_project to it
Cleaned up some docstrings