Make vault_server fixtures module-scoped
We are observing pipeline failures caused by single test using
`optional_vault_server`, which fails with:

> Error: Failed to authenticate to HashiCorp Vault 10.10.10.10:8200

The fixture was function-scoped, so it was executed about 20 times
during a single pipeline run. Turning it into module scope reduces the
number of executions to just 2. This doesn't really fix the underlying
problem, but reduces the surface and hopefully makes a problem
sufficiently rare.